# AUTO-GENERATED by generate_schema.py, DO NOT EDIT

VERSIONS: tuple[str, ...] = (
    "v0.56.1",
    "v0.56.0",
    "v0.55.4",
    "v0.55.3",
    "v0.55.2",
    "v0.55.1",
    "v0.55.0",
    "v0.54.3",
    "v0.54.2",
)

SNAPSHOTS: frozenset[str] = frozenset(
    {
        "v0.56.1",
        "v0.54.3",
    }
)
