# AUTO-GENERATED by generate_schema.py, DO NOT EDIT

VERSIONS: tuple[str, ...] = (
    "v0.55.0",
    "v0.54.3",
    "v0.54.2",
)

SNAPSHOTS: frozenset[str] = frozenset(
    {
        "v0.55.0",
        "v0.54.3",
    }
)
